# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

let
  kernelVersion = pkgs.linuxPackages_6_0;
in
{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    kernelPackages = kernelVersion;

    extraModulePackages = with pkgs; [
      kernelVersion.v4l2loopback 
      kernelVersion.acpi_call
    ];

    consoleLogLevel = 1;

    # Sysctl params
    kernel.sysctl = {
      # Allow VS Code to watch more files
      "fs.inotify.max_user_watches" = 524288;
      "vm.swappiness" = lib.mkDefault 1;
    };

    kernelModules = [ 
      "v4l2loopback" 
      "acpi_call" 
      "kvm-intel"
    ];

    kernelParams = [ 
      "quiet"
      "splash"
      "vga=current"
      "i915.fastboot=1"
      "loglevel=3"
      "udev.log_priority=3"
      "systemd.show_status=auto"
    ];

  };
  
  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

}