# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  nixpkgs.overlays = [ (import ../../misc/packages) ];
  
  boot = {
    plymouth = {
      enable = true;
      # https://sidhartharya.me/using-custom-plymouth-theme-on-nixos/
      # https://github.com/adi1090x/plymouth-themes
      themePackages = [ pkgs.adi1090x-plymouth ];
      theme = "dragon";
    };

    initrd = {
      availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
      kernelModules = [ "vfat" "nls_cp437" "nls_iso8859-1" "usbhid" ];

      luks = {
        # Support for Yubikey PBA
        yubikeySupport = true;

        devices."encrypted" = {
          device = "/dev/disk/by-label/NIXROOT"; # Be sure to update this to the correct volume

          yubikey = {
            slot = 2;
            twoFactor = false; # Set to false for 1FA
            gracePeriod = 30; # Time in seconds to wait for Yubikey to be inserted
            keyLength = 64; # Set to $KEY_LENGTH/8
            saltLength = 16; # Set to $SALT_LENGTH

            storage = {
              device = "/dev/sdb1"; # Be sure to update this to the correct volume
              fsType = "vfat";
              path = "/crypt-storage/default";
            };
          };
        };
      };
    };
  };

  fileSystems."/" =
    { device = "/dev/disk/by-label/nixos";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/BOOT";
      fsType = "vfat";
    };

  fileSystems."/nfs" =
    {
      mountPoint = "/nfs";
      device = "192.168.1.239:/volume1/fishhead";
      fsType = "nfs";
    };

}