# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{ 
  networking = {
    hostName = "dell";
    interfaces.enp59s0.useDHCP = true;
    interfaces.wlp0s20f3.useDHCP = true;
    firewall.allowedTCPPorts = [ 9100 ]; # printer
  };
}