# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot = {                                      # Boot options
    initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "virtio_balloon" "virtio_blk" "virtio_pci" "virtio_ring" ];
    initrd.kernelModules = [ ];
    kernelModules = [ ];
    extraModulePackages = [ ];

    loader = {                                  # For legacy boot:
      grub = {
        enable = true;
        version = 2;
        device = "/dev/vda";                    # Name of harddrive (can also be vda)
      };
      timeout = 1;                              # Grub auto select time
    };
  };

  fileSystems."/" =
    { device = "/dev/disk/by-label/nixos";
      fsType = "ext4";
    };
  
  services.openssh.enable = true;

  networking = {
    useDHCP = false;                        # Deprecated
    hostName = "vm";
    interfaces.eth0.useDHCP = true;
    interfaces.br0.useDHCP = true;
    bridges = {
      "br0" = {
        interfaces = [ "eth0" ];
      };
    };
  };

  

  users.users.root.password = "Init1234";
  users.users.fishhead.password = "Init1234";
  systemd.services.qemu-guest-agent.path = [ pkgs.shadow ];

}
